# @package _global_
denoiser:
  _target_: noise2same.denoiser.Noise2SelfDeconvolution
  n_dim: ${dataset.n_dim}
  in_channels: ${dataset.n_channels}
  masking: gaussian
  noise_mean: 0
  noise_std: 0.2
  regularization_key: image
  lambda_bound: 0
  lambda_sharp: 0