# @package _global_
denoiser:
  _target_: noise2same.denoiser.Noise2Same
  n_dim: 2
  in_channels: 1
  masking: gaussian
  noise_mean: 0
  noise_std: 0.2
  lambda_rec: 1.0
  lambda_inv: 2.0
  lambda_bsp: 0.0