hydra:
  run:
    dir: results/${experiment}/${backbone_name}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

cwd: ${hydra:runtime.cwd}

project: noise2same
device: 0
seed: 56
check: False
evaluate: True

training:
  steps_per_epoch: 1000
  steps: 50000
  batch_size: 64
  num_workers: 8
  crop: 64
  validate: True
  val_partition: 1.0
  val_batch_size: 4
  monitor: bsp_mse
  amp: True

dataset:
  n_dim: 2
  n_channels: 1
  standardize: True  # subtract mean and divide by std for each image separately

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0004
  weight_decay: 0

scheduler:
  _target_: noise2same.scheduler.ExponentialDecayScheduler
  _partial_: true
  decay_rate: 0.5
  decay_steps: 5e3  # how many steps to decrease by decay rate
  staircase: True  # integer division