hydra:
  run:
    dir: results/${now:%Y-%m-%d_%H-%M-%S}

project: noise2same
device: 0
seed: 56
check: False

data: bsd68

loader:
  batch_size: 8
  num_workers: 4

network:
  base_channels: 96
  kernel_size: 3
  depth: 3
  encoding_block_sizes: [1, 1, 0]
  decoding_block_sizes: [1, 1]
  downsampling: [conv, conv]
  skip_method: concat

train:
  n_epochs: 20