# @package _global_
backbone_name: swinia

backbone:
  _target_: noise2same.backbone.swinia.SwinIA
  _partial_: true  # to recalculate some parameters in code
  embed_dim: 144
  window_size: 8
  depths: [ 4, 4, 4, 4, 4 ]
  num_heads: [ 16, 16, 16, 16, 16 ]
  dilations: [ 1, 1, 1, 1, 1 ]
  shuffles: [ 1, 2, 4, 2, 1 ]

head:
  _target_: torch.nn.Identity

optim:
  lr: 1e-3
  scheduler: cosine
  eta_min: 1e-6