# @package _global_
backbone_name: swinia

backbone:
  embed_dim: 96
  window_size: 8
  depths: [ 8, 4, 4, 4, 4, 4, 8 ]
  num_heads: [ 6, 6, 6, 6, 6, 6, 6 ]
  strides: [ 1, 2, 4, 8, 4, 2, 1 ]
  mode: shuffled
