# @package _global_
backbone_name: swinia

backbone:
  embed_dim: 144
  window_size: 8
  depths: [ 8, 8, 8, 8, 8 ]
  num_heads: [ 16, 16, 16, 16, 16 ]
  dilations: [ 1, 1, 1, 1, 1 ]
  shuffles: [ 1, 2, 4, 2, 1 ]

optim:
  lr: 1e-3
  scheduler: cosine
  eta_min: 1e-6