# @package _global_
backbone_name: unet

backbone:
  _target_: noise2same.backbone.unet.UNet
  in_channels: ${dataset.n_channels}
  n_dim: ${dataset.n_dim}
  base_channels: 96
  kernel_size: 3
  depth: 3
  encoding_block_sizes: [ 1, 1, 0 ]
  decoding_block_sizes: [ 1, 1 ]
  downsampling: [ conv, conv ]
  downsampling_factor: [ 2, 2 ]
  skip_method: concat
  pad_divisor: ${eval:2 ** ${.depth}}  # used in dataset config

head:
  _target_: noise2same.backbone.unet.RegressionHead
  in_channels: ${backbone.base_channels}
  out_channels: ${dataset.n_channels}
  n_dim: ${dataset.n_dim}

scheduler:
  _target_: noise2same.scheduler.ExponentialDecayScheduler
  decay_rate: 0.5
  decay_steps: 5e3  # how many steps to decrease by decay rate
  staircase: True  # integer division