# @package _global_
backbone_name: unet

backbone:
  base_channels: 96
  kernel_size: 3
  depth: 3
  encoding_block_sizes: [ 1, 1, 0 ]
  decoding_block_sizes: [ 1, 1 ]
  downsampling: [ conv, conv ]
  skip_method: concat
